version: "3"

services:
  db:
    container_name: db
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: ./app
    command: bash -c "uvicorn app.src.main:app --host 0.0.0.0 --port 3030 --reload" # alembic upgrade head &&
    restart: always
    volumes:
      - ./app:/code/app
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432

  front:
    build:
      context: ./front
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './front:/app'


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
