version: "3"

services:
#  db:
#    image: postgres:11
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=test_db
  web:
    build:
      context: ./app
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 3030" # alembic upgrade head &&
    #volumes:
    #  - .:/code
    ports:
      - "3030:3030"
    #depends_on:
    #  - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432
#
#  front:
#    build:
#      context: ./front
#    ports:
#      - '8000:80'
#    volumes:
#      - './front:/app'


#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
