// : Generated by xaf-index-generator :

export { default as CommonButton } from './common.button.vue'
export { default as CommonInput } from './common.input.vue'
export { default as CommonModal } from './common.modal.vue'
export { default as CommonPopup } from './common.popup.vue'